# Generated by Django 4.1.7 on 2023-03-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_candidaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tb_listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('cod_color', models.CharField(max_length=10)),
                ('slogan', models.CharField(max_length=250)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tb_propuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tb_proceso_electoral',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='tb_lista_propuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tb_listas')),
                ('propuestas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tb_propuestas')),
            ],
        ),
    ]
